# Generated by Django 5.1a1 on 2024-06-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.IntegerField()),
                ('normalized_range', models.IntegerField()),
            ],
        ),
    ]
