# Generated by Django 5.1a1 on 2024-06-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_polit'),
    ]

    operations = [
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.IntegerField()),
                ('normalized_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.IntegerField()),
                ('normalized_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.IntegerField()),
                ('normalized_range', models.IntegerField()),
            ],
        ),
    ]
