# Generated by Django 5.1a1 on 2024-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_e_hist_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bi_pe',
            name='normalized_freq',
        ),
        migrations.RemoveField(
            model_name='e',
            name='normalized_freq',
        ),
        migrations.RemoveField(
            model_name='hist',
            name='normalized_freq',
        ),
        migrations.RemoveField(
            model_name='law',
            name='normalized_freq',
        ),
        migrations.RemoveField(
            model_name='m',
            name='normalized_freq',
        ),
        migrations.RemoveField(
            model_name='main',
            name='normalized_freq',
        ),
        migrations.RemoveField(
            model_name='polit',
            name='normalized_freq',
        ),
        migrations.AlterField(
            model_name='bi_pe',
            name='normalized_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='e',
            name='normalized_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hist',
            name='normalized_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='law',
            name='normalized_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='m',
            name='normalized_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='normalized_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='polit',
            name='normalized_range',
            field=models.FloatField(),
        ),
    ]
