# Generated by Django 5.1a1 on 2024-06-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_bi_pe_normalized_freq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bi_pe',
            name='normalized_freq',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='e',
            name='normalized_freq',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hist',
            name='normalized_freq',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='law',
            name='normalized_freq',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m',
            name='normalized_freq',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='normalized_freq',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polit',
            name='normalized_freq',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
