# Generated by Django 5.1a1 on 2024-06-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bi_pe_normalized_freq_e_normalized_freq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BI_PE_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='E_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HIST_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LAW_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Main_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='POLIT_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
    ]
