# Generated by Django 5.1a1 on 2024-07-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bi_pe_ngram_e_ngram_hist_ngram_law_ngram_m_ngram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_pecase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('sex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='school_pecase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('sex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='uni_pecase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('sex', models.TextField()),
            ],
        ),
    ]
