# Generated by Django 5.1a1 on 2024-07-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_school_pecase_fem_school_pecase_man_uni_pecase_fem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_pecase_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='school_pecase_fem_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='school_pecase_man_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='school_pecase_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uni_pecase_fem_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uni_pecase_man_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uni_pecase_mf_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uni_pecase_ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('rank', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('range', models.IntegerField()),
                ('normalized_freq', models.FloatField()),
                ('normalized_range', models.FloatField()),
                ('ngram', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='main_pecase',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='school_pecase',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='school_pecase_fem',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='school_pecase_man',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='uni_pecase',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='uni_pecase_fem',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='uni_pecase_man',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='uni_pecase_mf',
            name='sex',
        ),
    ]
